### ISSUE TITLE
Cell wrap

### ISSUE THREAD

**Issue by vincentarelbundock** [etiennebacher/altdoc#289] opened 2024-08-12 17:40 UTC
I tried to investigate this, but couldn't figure it out.

Why is the second column of the "Arguments" table not word-wrapped here? 

https://grantmcdermott.com/tinyplot/man/tinyplot.html

**Comment by etiennebacher** [comment] 2024-08-13 07:02
This was due to weird `\verb{}` tags in the Rd files that were caused by a typo in the original docs: https://github.com/etiennebacher/altdoc/issues/289.

Closing since there's nothing to do on our side (except maybe reporting this weird case to `roxygen2`)

**Closed by etiennebacher** 2024-08-13 07:02 UTC

**Comment by etiennebacher** [comment] 2024-08-13 07:14
Worth noting that this is likely not a bug in `roxygen2`. It seems that when the code in backticks is valid R code, it is wrapped in `\code{}` but if it's not it's wrapped in `\verb{}`:

``` r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' @title Foo
  #' @param axes Some text: `1 + 1`
  foo <- function() {}
")
```
```
$foo.Rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in ./<text>
\name{foo}
\alias{foo}
\title{Foo}
\usage{
foo()
}
\arguments{
\item{axes}{Some text: \code{1 + 1}}
}
\description{
Foo
}
```
```r
roxygen2::roc_proc_text(roxygen2::rd_roclet(), "
  #' @title Foo
  #' @param axes Some text: `1 1`
  foo <- function() {}
")
```

```
```

**Comment by vincentarelbundock** [comment] 2024-08-13 12:14
What a weird issue. And amazing investigation. Thanks for taking the time!
