### ISSUE TITLE
Quarto adds `.png` file extension automatically and incorrectly

### ISSUE THREAD

**Issue by grantmcdermott** [etiennebacher/altdoc#178] opened 2023-11-28 19:14 UTC
First discovered over at [plot2](https://github.com/grantmcdermott/plot2). You can see that my r-universe badge on the README is failing.

It looks like the badge error is due to **altdoc** re-rendering the README file and then appending ".png" on the badge link, i.e. instead of 

`https://grantmcdermott.r-universe.dev/badges/plot2`

we get

`https://grantmcdermott.r-universe.dev/badges/plot2.png`

I can fix it locally by knitting the README file manually, but then I'm worried that the R-chunk knitted PNG images won't appear (since these are assigned a new path, right?)

**Comment by vincentarelbundock** [comment] 2023-11-29 02:19
Ah thanks for this. I'll look into when I find time. Almost definitely my fault.

**Comment by grantmcdermott** [comment] 2023-12-04 04:22
Thanks @vincentarelbundock. Just merged but I think there's still an error: The trailing ".png," shouldn't be there at the end.

In other words, it should be this...
https://grantmcdermott.r-universe.dev/badges/plot2

... not this.
https://grantmcdermott.r-universe.dev/badges/plot2.png

**Comment by vincentarelbundock** [comment] 2023-12-04 10:15
Fixed here by adding a line to the preamble we store in `altdoc/` and making `.import_readme()` use it: https://github.com/etiennebacher/altdoc/pull/190

This won't fix it when README is a `.Rmd` file. I'm not sure if there's a similar option there. If there is, all we'd need to do is add the option to `inst/preamble_vignettes_rmd.yml`

**Closed** 2023-12-04 10:20 UTC

**Comment by grantmcdermott** [comment] 2024-03-10 19:29
Sorry to resurrect an old issue, but this is failing for me again on (the new) `tinyplot` website: https://grantmcdermott.com/tinyplot/

We moved to Quarto a while back and AFAICT it's been broken since. (I've been manually editing the rendered README.md file to at least get the GitHub landing page looking good.)

**Comment by vincentarelbundock** [comment] 2024-03-10 20:32
I don't there's anything `altdoc` should do about this. Any solution would be very hack-y and error prone.

The problem is that Quarto tries to be "helpful", but that its automagic feature breaks on R-universe links.

Details: Quarto inserts .png automatically when using the []() syntax for images and when there is no extension to the image path. R-universe badges are hosted on a website with a link without extension.

I just merged a pull request to `tinyplot` to fix this, but simply using a normal HTML link tag instead of markdown syntax.

**Comment by etiennebacher** [comment] 2024-03-10 21:50
Note that as of `quarto` 1.4 (the R package, not just the general software), we can use the `quarto_args` argument in `quarto_render()` to pass arguments that are not individually supported. For example, my reprex above can be fixed by calling `quarto::quarto_render("foo.qmd", output_format = "markdown", quarto_args = c("--default-image-extension", ""))`. I think that would allow us to greatly simplify the internals by removing all the "custom preamble" stuff
